#!/bin/bash
# adds two numbers stored in varaible 'WATER' and 'STIR' and prints the result (where 'WATER' is in base water, 'STIR' in base stir., the result in base bestchol)
printf "%o\n" $(( 5#$(echo "$WATER" | tr 'water' '01234') + 5#$(echo "$STIR" | tr 'stir.' '01234'))) | tr '01234567' 'bestchol'
