#!/usr/bin/env bash
# displays listening ports that only shows listening sockets and shows the PID and name of the program to which each socket belong
#+ Note: a specific IP + port = socket
#+ netstat  -  Print  network connections, routing tables, interface statistics, masquerade connections, and multicast memberships
netstat -lp
