#!/usr/bin/env bash
# display the content of the file '/etc/passwd' (should display only username, userid, home directory path for the user)
while read -r line; do
    echo "$line" | cut -d':' -f 1,3,6
done < "/etc/passwd"
