#!/usr/bin/env bash
# groups visitors by IP and HTTP status code, and display in this format (#occurence IP HTTP_CODE)
awk '{ print $1, $9 }' < "apache-access.log" | sort --key=1 | uniq -c | sort -r --key=1
