#!/usr/bin/env bash
# display the time for 12 hours and 59 minute (display hours from 0-12, minutes from 1-59)
i=0;
while [[ i -le 12 ]]; do
    echo "Hour: $i"
    j=1;
    while [[ j -lt 60 ]]; do
        echo "$j";
        (( j++ ))
    done;
    (( i++ ))
done;
