#!/usr/bin/env bash
# gives information about 'school' file (using only if and else (case forbidden))
FILE=$1;
echo "$FILE"
if [[ -e "$FILE" ]]; then
    echo "school file exists"
    if [[ -s "$FILE" ]]; then
        echo "school file is not empty";
    else
        echo "school file is empty";
    fi
    if [[ -f "$FILE" ]]; then
        echo "school is a regular file";
    fi
else
    echo "school file does not exist";
fi
