#!/usr/bin/env bash
# configures an Ubuntu server by resolving the localhost to 127.0.0.2, and facebook.com to 8.8.8.8

cp /etc/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
rm ~/hosts.new
